# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: lambda-best-practice
# app: lambda-best-practice-app
# org: minhnguyenvan

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
plugins:
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage,'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:BatchWriteItem"
      Resource: "*"
  environment:
    DB_REGION: ${${self:custom.config}:DB_REGION}
    DB_ENDPOINT: ${${self:custom.config}:DB_ENDPOINT}
    DB_ACCESS_KEY_ID: ${${self:custom.config}:DB_ACCESS_KEY_ID}
    DB_SECRET_ACCESS_KEY: ${${self:custom.config}:DB_SECRET_ACCESS_KEY}
custom:
  dynamodb:
    stages:
      - dev
      - prod
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      test:
        sources:
        - table: users
          sources: [./lambda-best-practice/seeds/users.json]
        - table: toDos
          sources: [./lambda-best-practice/seeds/todos.json]
  config: file(./lambda-best-practice/config/env.${self:provider.stage}.json)

functions:
  hello:
    handler: lambda-best-practice/handler.getUsers
    events:
      - http: 
          path: /users
          method: GET
          cors: true
  update:
    handler: lambda-best-practice/handler.updateTodos
    events:
      - http: 
          path: /todos
          method: PUT
          cors: true
  insertUser:
    handler: lambda-best-practice/handler.insertUser
    events:
      - http: 
          path: /users
          method: POST
          cors: true
  createToDo: 
    handler: lambda-best-practice/handler.createToDo
    events:
      - http: 
          path: /todos
          method: POST
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    todosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: toDos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1